# Generated by Django 5.2.6 on 2025-09-26 16:37

from django.db import migrations
from django.db.migrations.state import Apps


def create_initial_data(apps: Apps, schema_editor):
    Status = apps.get_model('cash_flow', 'Status')
    CashFlowType = apps.get_model('cash_flow', 'CashFlowType')
    Category = apps.get_model('cash_flow', 'Category')
    Subcategory = apps.get_model('cash_flow', 'Subcategory')
    
    status_1 = Status(name='Бизнес')
    status_2 = Status(name='Личное')
    status_3 = Status(name='Налог')
    
    Status.objects.bulk_create([
        status_1,
        status_2,
        status_3,
    ])

    cash_flow_type_1 = CashFlowType(name='Списание')
    cash_flow_type_2 = CashFlowType(name='Пополнение')

    CashFlowType.objects.bulk_create([
        cash_flow_type_1,
        cash_flow_type_2,
    ])

    category_1 = Category(name='Инфраструктура', cash_flow_type_id=1)
    category_2 = Category(name='Маркетинг', cash_flow_type_id=1)

    Category.objects.bulk_create([
        category_1,
        category_2,
    ])

    subcategory_1 = Subcategory(name='VPS', category_id=1)
    subcategory_2 = Subcategory(name='Proxy', category_id=1)
    subcategory_3 = Subcategory(name='Farpost', category_id=2)
    subcategory_4 = Subcategory(name='Avito', category_id=2)

    Subcategory.objects.bulk_create([
        subcategory_1,
        subcategory_2,
        subcategory_3,
        subcategory_4,
    ])


def delete_initial_data(apps, schema_editor):
    Status = apps.get_model('cash_flow', 'Status')
    CashFlowType = apps.get_model('cash_flow', 'CashFlowType')
    Category = apps.get_model('cash_flow', 'Category')
    Subcategory = apps.get_model('cash_flow', 'Subcategory')
    
    Status.objects.all().delete()
    CashFlowType.objects.all().delete()
    Category.objects.all().delete()
    Subcategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, delete_initial_data)
    ]
